version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "acc15-flight-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-122j9xx9geic4"
s3_prefix = "acc15-flight-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
